app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
    path('kohli/',kohli,name='kohli'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('jadeja/',jadeja,name='jadeja'),
    path('rohit/',rohit,name='rohit'),
]

project17/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')



def kohli(request):
    return render(request,'kohli.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def jadeja(request):
    return render(request,'jadeja.html')




def rohit(request):
    return render(request,'rohit.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <center>
    <h1>welcome to dhoni html page</h1>
    <a href="{% url 'app1:kohli' %}">go to kohli page</a>
   </center> 
</body>
</html>

templates/jadeja.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to jadeja html web page</h1> 
        <a href="{% url 'app2:rohit'%}">go to rohit html page</a>
    </center>
</body>
</html>

templates/kohli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to kohli html page</h1>
        <a href="{% url 'app1:dhoni' %}">go to dhoni page</a>
    </center>
</body>
</html>

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to rohit html web page</h1>
        <a href="{% url 'app2:jadeja'%}">go to jadeja html page</a>
    </center>
</body>
</html>